// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_a68IlKiFXGTKdh-un_G-dpDuQmFpRc',
    appId: '1:656473241065:web:d21a1954b7b60c629b8778',
    messagingSenderId: '656473241065',
    projectId: 'myapp-7cf29',
    authDomain: 'myapp-7cf29.firebaseapp.com',
    storageBucket: 'myapp-7cf29.firebasestorage.app',
    measurementId: 'G-YVM2KTZ5YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnxgRBAfIlhCxtHqHHazMTaJhFaX3Qjdo',
    appId: '1:656473241065:android:5ccf2d443ea988c29b8778',
    messagingSenderId: '656473241065',
    projectId: 'myapp-7cf29',
    storageBucket: 'myapp-7cf29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkN1OqV6bVtCXdd080RxFwgKvr2Tk6Skw',
    appId: '1:656473241065:ios:c57ef970b3aa19a59b8778',
    messagingSenderId: '656473241065',
    projectId: 'myapp-7cf29',
    storageBucket: 'myapp-7cf29.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkN1OqV6bVtCXdd080RxFwgKvr2Tk6Skw',
    appId: '1:656473241065:ios:c57ef970b3aa19a59b8778',
    messagingSenderId: '656473241065',
    projectId: 'myapp-7cf29',
    storageBucket: 'myapp-7cf29.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-_a68IlKiFXGTKdh-un_G-dpDuQmFpRc',
    appId: '1:656473241065:web:8f4f189416ea27d99b8778',
    messagingSenderId: '656473241065',
    projectId: 'myapp-7cf29',
    authDomain: 'myapp-7cf29.firebaseapp.com',
    storageBucket: 'myapp-7cf29.firebasestorage.app',
    measurementId: 'G-C69QMG3SFH',
  );
}
